### ISSUE TITLE
'v' indicator does not move some letters to new location

### ISSUE THREAD

**Issue by ntuckertriplet** [TheToddLuci0/Anti-Wordle-Weaponry#1]
Tested against the word `moist`, marking `s` valid in `oreas` moved the `s` to position 0. This would be marked as a valid letter, but still wrong location, but in subsequent guesses, the `s` remained at position 0.

**Comment by ntuckertriplet** [comment]
<img width="638" alt="Screen Shot 2022-02-02 at 11 01 06 AM" src="https://user-images.githubusercontent.com/23064607/152201660-fa2af086-6255-4f1a-87af-8a9d4fbd6f07.png">

**Comment by TheToddLuci0** [comment]
The weapon does not currently track a list of where a valid letter is not allowed to be (in this case, the `s` in position 0). This is a known issues, and will hopefully be resolved in a future release.

**Comment by TheToddLuci0** [comment]
You also failed to mark the `o` in position 0 of `oreas` as a valid letter for your target word of `moist`, which caused the weapon to exclude it from the guess queue. causing the empty list error at the end.

**Comment by ntuckertriplet** [comment]
PEBKAC bites, it was able to land on `moist` when `o` was correctly marked

**Comment by ntuckertriplet** [comment]
<img width="626" alt="Screen Shot 2022-02-02 at 11 49 13 AM" src="https://user-images.githubusercontent.com/23064607/152209200-871377e8-561c-4cbc-84ef-c6dda042ccb6.png">
